### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by martiper71** [toolson12/pyprimitiva#8]
Buenos días.

No me deja acceder al RSS de la Lotería, me da el error IndexError: list index out of range. Si simplemente intento sacar los títulos del RSS no me saca nada con este código. Sin embargo si pongo un RSS con los videos de un canal de Youtube funciona perfectamente. Por lo que sospecho que es el formato del RSS de la Lotería.

# Lo primero que hacemos es importar el modulo feedparser:
import feedparser

# url =  'http://www.loteriasyapuestas.es/es/la-primitiva/resultados/.formatorss'
url = 'http://www.youtube.com/feeds/videos.xml?channel_id=UCWcp1Mwm7_bJ-mVoZb8TdkQ'

# Parsea el RSS desde la URL proporcionada
feed = feedparser.parse(url)

# Recorre los elementos <item> e imprime sus títulos
for item in feed.entries:
    print(item.title)

**Comment by toolson12** [comment]
Hola @martiper71 , 

¡Cuidado con las mayúsculas en la url de la Lotería! La url que indicas en el ejemplo, que acaba en .formatorss (en minúsculas) es diferente a la que devuelve con .formatoRSS (en mayúsculas, la que apunta el código original).

Verás que la que está en minúsculas [apunta a una página html](https://www.loteriasyapuestas.es/es/la-primitiva/resultados/.formatorss).

![image](https://github.com/toolson12/pyprimitiva/assets/56155834/e087a7a5-a65e-4f0b-91c3-d13ccd92fc7f)

[La url en mayúsculas apunta al xml sobre el que se parsea.](https://www.loteriasyapuestas.es/es/la-primitiva/resultados/.formatoRSS)

![image](https://github.com/toolson12/pyprimitiva/assets/56155834/f0661ba3-eab5-46b4-82b9-ec63f9e38428)


Saludos.

**Comment by martiper71** [comment]
Muchas gracias por responder.

Sí, de eso me di cuenta. Pero con RSS en mayúsculas tampoco funciona.

**Comment by martiper71** [comment]
Mira. Con la url1 funciona. Con la url2 de la lotería no.

`# Lo primero que hacemos es importar el modulo feedparser:
import feedparser

url1 = 'http://www.youtube.com/feeds/videos.xml?channel_id=UCWcp1Mwm7_bJ-mVoZb8TdkQ'
url2 = "http://www.loteriasyapuestas.es/es/la-primitiva/resultados/.formatoRSS"

# Parsear el feed RSS
rss = feedparser.parse(url1)

# Mostrar información general del feed
print(f'Título del feed: {rss.feed.title}')
print(f'Link del feed: {rss.feed.link}')

# Iterar a través de las entradas (elementos del feed)
for entry in rss.entries:
    print('-' * 40)
    print(f'Título de la entrada: {entry.title}')
    print(f'Enlace de la entrada: {entry.link}')
    print(f'Fecha de la entrada: {entry.published}')
    print(f'Descripción de la entrada: {entry.summary}')`

**Comment by toolson12** [comment]
He intentado reproducir el error y me devuelve correctamente la información de cada entrada del feed de la Lotería (url2).

Por ejemplo, lo correspondiente a `print(f'Título de la entrada: {entry.title}')`

----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 14 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 14 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 12 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 12 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 09 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 09 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 07 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 07 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 05 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 05 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 02 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 02 de octubre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 30 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 30 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 28 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 28 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 25 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: resultados del 25 de septiembre de 2023
----------------------------------------
Título de la entrada: La Primitiva: premios y ganadores del 23 de septiembre de 2023
----------------------------------------



Similar comportamiento cuando lo replico con `print(f'Enlace de la entrada: {entry.link}')` :


----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-14-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-14-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-12-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-12-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-09-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-09-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-07-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-07-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-05-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-05-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-02-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-02-de-octubre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-30-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-30-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-28-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-28-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-25-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/resultados/la-primitiva-resultados-del-25-de-septiembre-de-2023.formatoRSS
----------------------------------------
Enlace de la entrada: https://www.loteriasyapuestas.es/es/la-primitiva/escrutinios/la-primitiva-premios-y-ganadores-del-23-de-septiembre-de-2023.formatoRSS
----------------------------------------

**Comment by martiper71** [comment]
Pues estoy desesperado.

[https://imgur.com/C6FARFA](url)

Con la url1 me funciona pero con la url2.

Gracias por la respuesta

**Comment by toolson12** [comment]
Te sugeriría que intentes reproducir el problema desde otra red por si acaso estás detrás de un proxy que impide al programa leer el xml remoto.

Si te sirve de orientación, he intentado reproducir tu error en un Codespaces de Github y he obtenido los resultados correctos. 

Lamento no poder ayudarte más.

**Comment by martiper71** [comment]
Muchísimas gracias por tu amabilidad.
